<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <AssemblyName>ModMenu</AssemblyName>
    <Description>My first plugin</Description>
    <Version>1.0.0</Version>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>latest</LangVersion>
    <GameBaseDir>F:\Steam\steamapps\common\White Knuckle</GameBaseDir>
    <GameAssemblyDir>$(GameBaseDir)\White Knuckle_Data\Managed</GameAssemblyDir>
    <PluginBuildDir>$(GameBaseDir)\BepInEx\plugins</PluginBuildDir>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BepInEx.Analyzers" Version="1.*" PrivateAssets="all" />
    <PackageReference Include="BepInEx.Core" Version="5.*" />
    <PackageReference Include="BepInEx.PluginInfoProps" Version="1.*" />
    <PackageReference Include="UnityEngine.Modules" Version="2022.3.62" IncludeAssets="compile" />
    <Reference Include="Assembly-CSharp">
      <HintPath>$(GameAssemblyDir)\Assembly-CSharp.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Assembly-CSharp-firstpass">
      <HintPath>$(GameAssemblyDir)\Assembly-CSharp-firstpass.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>$(GameAssemblyDir)\UnityEngine.UI.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Unity.TextMeshPro">
      <HintPath>$(GameAssemblyDir)\Unity.TextMeshPro.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="DarkMachineUI">
      <HintPath>$(GameAssemblyDir)\DarkMachineUI.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="WKLib">
      <HintPath>$(PluginBuildDir)\WKLib\WKLib.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Unity.InputSystem">
      <HintPath>$(GameAssemblyDir)\Unity.InputSystem.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>
  
  <ItemGroup Condition="'$(TargetFramework.TrimEnd(`0123456789`))' == 'net'">
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.2" PrivateAssets="all" />
  </ItemGroup>
  
  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="xcopy &quot;$(TargetPath)&quot; &quot;$(PluginBuildDir)&quot; /y&#xA;xcopy &quot;$(TargetDir)$(ProjectName).pdb&quot; &quot;$(PluginBuildDir)&quot; /y" />
  </Target>
</Project>
